### PR TITLE
Added InlineRequests

### PR DESCRIPTION
**Pull request by simeonschaub**

### CODE REVIEW

**Review by Moelf — COMMENTED** [review]
Thx for contributing, but I can't seem to get it to work.
Do you need to tune any Bot settings in telegram for this to work?

**Comment by simeonschaub** [comment]
Yes, you need to enable it with the BotFather's /setinline command

**Comment by Moelf** [comment]
I have that enabled and I also gave it some placeholder, but when I @ my bot in a group chat, and put some text into it nothing shows up. And I don't see anything shows up in https://api.telegram.org/<bot_api>/getUpdates, which is where we getUpdates from?

**Comment by simeonschaub** [comment]
That's weird. Did you use the example in README.md? Do regular messages work?

**Comment by Moelf** [comment]
Yea I copied the example in REAME which didn't work 
(and also found a bug where welcomMsg don't accept `incoming::AbstractString`.)
My biggest question is why nothing shows up in the api /getUpdates page.

**Comment by simeonschaub** [comment]
Could you double check if your bot is configured correctly? If it doesn't show up in getUpdates, there has to bd a problem with the bot itself. I'm using this code right now with my bot and everything works fine. The only thing might be, that when you send the same InlineQuery twice, it uses the previous cached result from the server, which might be why it doesn't show up.

**Comment by Moelf** [comment]
I stopped running all the instances of my bot and manually openning browser to look at api/getUpdates and see nothing related to the inline query.

One thing though, for my bot it seems that telegram is waiting for server to respond, I can't really send an inline message because once I entered `@ mybot <text>` the send button becomes a loading button.

**Comment by simeonschaub** [comment]
You were right, welcomeMsg needs to accept a parameter, but other than that, the example works perfectly fine for me. The only thing I could still think of, did you put "bot" in front of your API key? This should probably be be done inside the module, but I didn't want to break existing code. Also, is the space after the @ a typo, because this could also be the reason it doesn't work.

**Comment by Moelf** [comment]
Yes that was a typo in my comment. I created a new bot and it seems inline query can be seen normally in the webpage, I will figure out what's going on and merge your PR. Thx again for the awesome contribution, first time actually receiving help!

**Comment by simeonschaub** [comment]
Glad to contribute, seems like a cool project!

**Pull request merged**
